// District -> Block -> IVCS list (source: IVCS__Survey_1.xlsx, "IVCS Farmers Count- Block Wise")
// Generated - do not edit by hand; 503 IVCS across 11 districts.
const IVCS_DATA = {
 "EGH": {
  "Dambo Rongjeng": [
   "Baringgre Wadro IVCS Ltd",
   "Chitil Apal IVCS Ltd",
   "Dambo Rongdeng IVCS Ltd",
   "Darugre Chikama IVCS Ltd",
   "Gabil Daningka IVCS Ltd",
   "Gabil Rongmil IVCS Ltd",
   "Haslong Nagimaram IVCS Ltd",
   "Mangsang Bamil IVCS Ltd",
   "Millawe Songma IVCS Ltd",
   "Ronga Agal Nengkram Imthra IVCS Ltd",
   "Rongdu IVCS Ltd",
   "Rongjeng Reserve Jakusan IVCS Ltd",
   "Silchang Dimrimbri Palwang Ading IVCS Ltd",
   "Upper Nongbak Apal IVCS Ltd",
   "Werambri IVCS Ltd",
   "Nongchram IVCS Ltd (EGH)",
   "SUNDARE IVCS Ltd (EGH)",
   "Sarang Apal IVCS Ltd",
   "Naringgre IVCS Ltd",
   "Anchengbok IVCS"
  ],
  "Samanda": [
   "Tongbolgre Green Hills IVCS Ltd",
   "Dobetkolgre IVCS Ltd",
   "Rongsak IVCS Ltd"
  ],
  "Songsak": [
   "Asil Dikagre IVCS Ltd",
   "Barikgre IVCS Ltd",
   "Bolmoram Adik Chibasal IVCS Ltd",
   "Bonepa IVCS Ltd",
   "Chram IVCS Ltd",
   "Dechakki IVCS Ltd",
   "Donrime IVCS Ltd",
   "Gongrang IVCS Ltd",
   "Kosi IVCS Ltd",
   "The Matwa Apal IVCS Ltd",
   "Napak IVCS Ltd",
   "Norek IVCS Ltd",
   "Rongbitchi IVCS Ltd",
   "Bolchurani IVCS Ltd",
   "Tebil Bonegre IVCS Ltd",
   "Tengsuram IVCS Ltd",
   "Upper Bolmoram IVCS Ltd",
   "Bolmoram Angkekol IVCS Ltd",
   "Sawegre IVCS Ltd",
   "Bone Watregre IVCS Ltd",
   "Jamge IVCS Ltd",
   "Changmandal IVCS Ltd",
   "Chikasin IVCS Ltd"
  ]
 },
 "EJH": {
  "Khliehriat": [
   "Cham Cham IVCS Ltd",
   "Iapmala IVCS Ltd",
   "Iongkaluh IVCS Ltd",
   "Lumshyrmit IVCS Ltd",
   "Mukhaialong IVCS Ltd",
   "Mutong IVCS Ltd",
   "Myntoilang IVCS Ltd",
   "Rangad IVCS Ltd",
   "Shirup U Krehlang IVCS Ltd",
   "Sohkymphor Mission IVCS Ltd",
   "Suchen IVCS Ltd",
   "Thmu Deimiat Hingaria IVCS Ltd",
   "Tubershohshrieh IVCS Ltd",
   "Tyllilang IVCS Ltd (EJH)",
   "Wapung Shnong IVCS Ltd",
   "Wapung Skur IVCS Ltd",
   "Iengskhem IVCS Ltd",
   "Jalyiah IVCS Ltd",
   "Tuber Kmaishnong IVCS Ltd",
   "Umlyngsha IVCS Ltd",
   "Wahsarang IVCS Ltd",
   "Khliehmyntriang IVCS Ltd",
   "Byrwai IVCS Ltd",
   "Umkiang IVCS Ltd",
   "Pamrakmai IVCS Ltd",
   "Samasi IVCS Ltd",
   "Jalaphet Bri Sumer IVCS Ltd",
   "Moolamanoh IVCS Ltd",
   "Pamrapaithlu IVCS Ltd",
   "Jalaphet Bri Sutnga IVCS Ltd",
   "Narwan IVCS Ltd",
   "Lawei Phyrnai IVCS Ltd"
  ]
 },
 "EKH": {
  "Laitkroh Khatarshnong": [
   "Diengkynthong IVCS Ltd",
   "Khrang IVCS Ltd",
   "Kyrdemkhla IVCS Ltd",
   "Laitlyndop IVCS Ltd",
   "Laitmawlong Wahpein IVCS Ltd",
   "Laitmawroh Ramkheng IVCS Ltd",
   "Mawbeh IVCS Ltd",
   "Mawlyndiar IVCS Ltd",
   "Mawmihthied IVCS Ltd",
   "Raid Mawshuit IVCS Ltd",
   "Nongthymmai Lumthangding IVCS Ltd",
   "Sohrarim IVCS Ltd",
   "Swer IVCS Ltd",
   "Mawrah-Rangtmah IVCS Ltd",
   "Ladmawphlang IVCS Ltd",
   "Raid Warbah IVCS Ltd",
   "Umlympung 12Mer Mylliem IVCS Ltd",
   "Umdiengpoh Laitthemlangsah IVCS Ltd"
  ],
  "Mawkynrew": [
   "Jatah Nonglyer IVCS Ltd",
   "Laitkyrhong IVCS Ltd",
   "Syntung IVCS Ltd"
  ],
  "Mawlai": [
   "Iaryntihlang IVCS"
  ],
  "Mawpat": [
   "Nongmensong IVCS"
  ],
  "Mawphlang": [
   "Domsnion IVCS Ltd",
   "Dongiewrim IVCS Ltd",
   "Jabar Lumtop Jaud IVCS Ltd",
   "Jamynthlen IVCS Ltd",
   "Krang Nonglum IVCS Ltd",
   "Kyiem IVCS Ltd",
   "Laitnongrim Nangkiew Shaphrang IVCS Ltd",
   "Mawlum Rum Nangkyntiew IVCS Ltd",
   "Mawmaram IVCS Ltd",
   "Mawthlong Mynsain IVCS Ltd",
   "Mawthwan IVCS Ltd",
   "Nongur IVCS Ltd",
   "Pyndenglitha IVCS Ltd",
   "Wahsohlait IVCS Ltd",
   "Pyndengkhah IVCS"
  ],
  "Mawryngkneng": [
   "Puriang IVCS Ltd",
   "Mawiong IVCS Ltd"
  ],
  "Mawsynram": [
   "Tehsongkawei IVCS Ltd",
   "Mawkasain IVCS Ltd",
   "Phlangmawsyrpat"
  ],
  "Mylliem": [
   "Rangbihbih IVCS Ltd"
  ],
  "Pynursla": [
   "Btinlangti IVCS Ltd",
   "Lapalang IVCS Ltd",
   "Pynter IVCS Ltd",
   "Pyrnai IVCS Ltd",
   "Laitmynrieng IVCS Ltd",
   "Nongshken IVCS Ltd",
   "Wahkdait IVCS Ltd",
   "Umsyiem IVCS Ltd"
  ],
  "Shella Bholaganj": [
   "Laitiam IVCS Ltd",
   "Laittyra IVCS Ltd",
   "Mawkisyiem IVCS Ltd",
   "Mustoh IVCS Ltd",
   "Nongduh IVCS Ltd",
   "Nongsteng IVCS Ltd",
   "Suktia inc Diengsiar IVCS Ltd",
   "Umsawmaskon IVCS Ltd",
   "Wahkaliar IVCS Ltd",
   "Tyrna IVCS Ltd",
   "Sohlap Umdoh Mawpot IVCS Ltd",
   "Saitsohpen IVCS Ltd"
  ],
  "Sohiong": [
   "Lumlang IVCS Ltd",
   "Jingiatreilang IVCS Ltd"
  ]
 },
 "EWKH": {
  "Mairang": [
   "Mawnai IVCS Ltd",
   "Iaipyrshang IVCS Ltd",
   "Mawlyntriang IVCS Ltd",
   "Nongrmai IVCS Ltd",
   "Rikhen IVCS Ltd",
   "Ksehkohmoit IVCS Ltd",
   "Mawblei IVCS Ltd"
  ],
  "Mawshynrut": [
   "Kyrshanlum IVCS Ltd"
  ],
  "Mawthadraishan": [
   "Nongkasen IVCS Ltd",
   "Marngor IVCS Ltd",
   "Mawkamoit IVCS Ltd",
   "Tur Shaphrang IVCS Ltd",
   "Mawkohngei IVCS Ltd",
   "Nonglait IVCS Ltd",
   "Mawlangren IVCS Ltd",
   "Suk Ban Rep IVCS Ltd",
   "Nangkiew Mawlangkhar IVCS Ltd"
  ]
 },
 "NGH": {
  "Adokgre": [
   "Sokchuan IVCS Ltd"
  ],
  "Bajengdoba": [
   "Pangchakram IVCS Ltd",
   "Jiban IVCS Ltd",
   "Gabil IVCS Ltd",
   "Dokua IVCS Ltd",
   "Korepara IVCS Ltd",
   "Balkolgre IVCS Ltd"
  ],
  "Kharkutta": [
   "Bakrime IVCS Ltd (NGH)",
   "Balgito IVCS Ltd",
   "Chibasal IVCS Ltd (NGH)",
   "Dapolpara Local Development Association IVCS Ltd",
   "Krimko IVCS Ltd (NGH)",
   "Krimsan IVCS Ltd",
   "Kucholsan IVCS Ltd (NGH)",
   "Mangkima IVCS Ltd",
   "Mendima IVCS Ltd",
   "Nangrime IVCS Ltd (NGH)",
   "Rajasimla Chokchimsa IVCS Ltd",
   "Sengga IVCS Ltd",
   "Sonaru IVCS Ltd",
   "Songbri IVCS Ltd",
   "Tangkamgipa IVCS Ltd",
   "Tinsimina IVCS Ltd",
   "Upper Kharkutta Four Brothers IVCS Ltd",
   "Songchet Nangrime IVCS Ltd",
   "Nehru IVCS Ltd",
   "Kentra IVCS Ltd"
  ]
 },
 "RB": {
  "Bhoirymbong": [
   "Kdonghulu Multipurpose Cooperative Society Ltd",
   "Pynimlang IVCS Ltd",
   "Kynhun Dorbar Umktieh IVCS Ltd"
  ],
  "Jirang": [
   "Mynnar Jirang IVCS Ltd",
   "Wahsynnon IVCS Ltd",
   "Kyntiewlang IVCS Ltd",
   "Kynjohshaphrang IVCS Ltd",
   "Umtangar IVCS Ltd",
   "Iaryngkatlang IVCS Ltd",
   "Ialumlang IVCS Ltd"
  ],
  "Umling": [
   "Kuswai Area IVCS Ltd",
   "Marmain IVCS Ltd",
   "Mawlong Nongtluh IVCS Ltd",
   "Mawphru Mathan IVCS Ltd",
   "Nongkhrah IVCS Ltd",
   "Nonglyngdoh IVCS Ltd",
   "Sarikushi IVCS Ltd",
   "Sohlait IVCS Ltd",
   "Umdap Pyllun IVCS Ltd",
   "Umden Pyllun IVCS Ltd",
   "Umdihar IVCS Ltd",
   "Umkaduh IVCS Ltd",
   "Umkon IVCS Ltd",
   "Umling IVCS Ltd",
   "Umsaw Nongbri IVCS Ltd",
   "Umshaken IVCS Ltd",
   "Umwang Pyllun IVCS Ltd",
   "Mawphrow IVCS Ltd",
   "Pillingkata-B IVCS Ltd",
   "Shangbangla IVCS Ltd",
   "Santipur IVCS Ltd",
   "Tengsua IVCS Ltd",
   "Mawkangi Synroplang IVCS Ltd",
   "Niangbari Cooperative Society Ltd"
  ],
  "Umsning": [
   "Sonidan Service Cooperative Society Ltd",
   "Maitshaphrang IVCS Ltd"
  ]
 },
 "SGH": {
  "Baghmara": [
   "Asokgre IVCS Ltd",
   "Chibasal IVCS Ltd (SGH)",
   "Chigitchak IVCS Ltd",
   "Choklokgittim IVCS Ltd",
   "Dabit IVCS Ltd",
   "Dabram IVCS Ltd",
   "Dasanggre IVCS Ltd",
   "Denggaggre IVCS Ltd",
   "Dorengo IVCS Ltd",
   "Eringgre IVCS Ltd",
   "Gangga IVCS Ltd",
   "Gatabil IVCS Ltd",
   "Goka IVCS Ltd",
   "Katchi-Garantai IVCS Ltd",
   "Kucholsan IVCS Ltd (SGH)",
   "Memang Koksi IVCS Ltd",
   "Upper Rongdotchi IVCS Ltd",
   "Balkal Asim IVCS Ltd",
   "Chibrenggre IVCS Ltd",
   "Dosogre IVCS Ltd",
   "Sibbari IVCS Ltd",
   "Jalaigre IVCS Ltd",
   "Nongalbibra IVCS Ltd",
   "REWAK IVCS"
  ],
  "Chokpot": [
   "Allagre IVCS Ltd",
   "Balwatgre Multipurpose Cooperative Society Ltd",
   "Bandarigre IVCS Ltd",
   "Budugre IVCS Ltd",
   "Dagal Songital IVCS Ltd",
   "Dumindigre IVCS Ltd",
   "Durabanda Chambugong IVCS Ltd",
   "Gongganggre IVCS Ltd",
   "Kenegre IVCS Ltd",
   "Mibonpara IVCS Ltd",
   "Rampragre IVCS Ltd",
   "Ritimgital IVCS Ltd",
   "Rongdi Bugai IVCS Ltd",
   "Silki A'chak Chiring IVCS Ltd",
   "Silki Batagre IVCS Ltd",
   "Simkalanggre IVCS Ltd",
   "Tangchaoe IVCS Ltd",
   "Bolchidamgre IVCS Ltd",
   "Jetragre IVCS Ltd",
   "Papa Songmong IVCS Ltd",
   "Damikchigre IVCS Ltd",
   "KARIJORAGRE IVCS Ltd"
  ],
  "Gasuapara": [
   "BamonBajra IVCS Ltd",
   "Gasuapara Songmong IVCS Ltd",
   "Dimagre IVCS Ltd",
   "Megua Songma IVCS Ltd",
   "Chengkali IVCS Ltd",
   "Wachira Eco Tourism Multipurpose Cooperative Society Ltd",
   "Kangkarkona Livestock Cooperative Society Ltd",
   "Bandapara Multipurpose Coperative Society Ltd"
  ],
  "RONGARA": [
   "Dambuk Apal IVCS Ltd",
   "Gaobari IVCS Ltd",
   "Mahadeo Service Cooperative Society"
  ]
 },
 "SWGH": {
  "Betasing": [
   "Goera IVCS Ltd",
   "Dream Four IVCS Ltd"
  ],
  "Purakhasia": [
   "Darong ADu Baptist Church IVCS Ltd",
   "Babelapara IVCS Ltd"
  ],
  "Rerapara": [
   "Matrongkol IVCS Ltd",
   "Dosadil IVCS Ltd",
   "Goramara IVCS Ltd",
   "Damalgre IVCS Ltd",
   "Grimsan Wegaa IVCS Ltd",
   "Matalagre Chiripram IVCS Ltd",
   "Rongchadenggre IVCS Ltd"
  ],
  "Zikzak": [
   "Baksapara IVCS Ltd",
   "Balughat IVCS Ltd",
   "Bolchugre IVCS Ltd",
   "Bollonggre B1 IVCS Ltd",
   "Bollonggre B IVCS Ltd",
   "Chapahati 1 IVCS Ltd",
   "Digligre IVCS Ltd",
   "Dimiligre IVCS Ltd",
   "Dingampara IVCS Ltd",
   "Domapara IVCS Ltd",
   "Dondima IVCS Ltd",
   "Hatibelpara IVCS Ltd",
   "Hullukona IVCS Ltd",
   "Kalaichar IVCS Ltd",
   "Kawahagra IVCS Ltd",
   "Kentrikona IVCS Ltd",
   "Kerupara IVCS Ltd",
   "Kuligre IVCS Ltd",
   "Saliram IVCS Ltd",
   "A'a Ki'tik IVCS Ltd",
   "Darapani IVCS Ltd"
  ],
  "Mawkyrwat": [
   "Rangblang Sohsynniang IVCS Ltd",
   "Mawkhyrwang Area IVCS Ltd / Sanshnong IVCS",
   "Mawlangwir IVCS Ltd",
   "Warsanlyngdoh IVCS Ltd",
   "Shgimawlein Nongbrei Nongdom IVCS Ltd",
   "Marshilong IVCS",
   "Kuparstar IVCS",
   "Mawthawiang IVCS"
  ],
  "Ranikor": [
   "Iaikyrsoi IVCS Ltd",
   "Keniong IVCS Ltd",
   "Koltapara IVCS Ltd",
   "Koraigora IVCS Ltd",
   "Lower Rajapara IVCS Ltd",
   "Mattilang IVCS Ltd",
   "Mawpud IVCS Ltd",
   "Mawpyllun IVCS Ltd",
   "Munaisora IVCS Ltd",
   "N.W.E. Rangasora IVCS Ltd",
   "Nongkdait Nongtwah IVCS Ltd",
   "Mawpait Nongthymmai IVCS Ltd",
   "Old Moilam IVCS Ltd",
   "Pamdaba IVCS Ltd",
   "Phlangdiloin IVCS Ltd",
   "Raibah IVCS Ltd",
   "Sarin IVCS Ltd",
   "Sodorkura Khasiadop IVCS Ltd",
   "Tillagao IVCS Ltd",
   "Iamonlang IVCS Ltd",
   "Tyllilang IVCS Ltd (SWKH)",
   "Khonjoy IVCS Ltd",
   "Helping Minds IVCS Ltd",
   "United Three Villages IVCS Ltd",
   "United Four Villages IVCS"
  ]
 },
 "WGH": {
  "Dadenggre": [
   "Ajigre IVCS Ltd",
   "Chandisila IVCS Ltd",
   "Chenggal Dare IVCS Ltd",
   "Chudoang IVCS Ltd",
   "Dallanggre IVCS Ltd",
   "Dokramgre IVCS Ltd",
   "Grimjong IVCS Ltd",
   "Kawak Dare IVCS Ltd",
   "Polpola IVCS Ltd",
   "Pringprang IVCS Ltd",
   "Rongtenabak IVCS Ltd",
   "Salak IVCS Ltd",
   "Salcharam IVCS Ltd",
   "Songadinggre IVCS Ltd",
   "Tangbang IVCS Ltd",
   "Dobakol IVCS Ltd",
   "Jarambong IVCS Ltd"
  ],
  "Dalu": [
   "Kumonggrik IVCS Ltd",
   "Thallang IVCS Ltd",
   "Bugi IVCS Ltd",
   "Norang Bogai IVCS Ltd",
   "Mikkasal IVCS Ltd",
   "Kucholsan IVCS Ltd (Dalu)",
   "Bandra IVCS Ltd",
   "Border IVCS Ltd"
  ],
  "Demdema": [
   "Hazarika IVCS Ltd",
   "Khurang IVCS Ltd",
   "Beautiful IVCS Ltd",
   "Sundare IVCS Ltd (WGH)",
   "Jakusan IVCS Ltd (Demdema)",
   "Bakrimesa IVCS Ltd",
   "Khetadawa Multipurpose Cooperative Society Ltd",
   "Jakusan Integrated Village Co-operative Society Ltd (Demdema)",
   "Muskan IVCS Ltd",
   "Matgrik IVCS Ltd"
  ],
  "Gambegre": [
   "Dimchrang IVCS Ltd",
   "Songsni Bakrime IVCS Ltd"
  ],
  "Selsella": [
   "Akawe IVCS Ltd",
   "Bakrime IVCS Ltd (Selsella)",
   "Cambda IVCS Ltd",
   "Chokchim IVCS Ltd",
   "Haripur IVCS Ltd",
   "Kalchengpara IVCS Ltd",
   "Kucholsan IVCS Ltd (Selsella)",
   "Kumonggrika IVCS Ltd",
   "Lower Shyamnagar IVCS Ltd",
   "Nangrimesa IVCS Ltd",
   "Radorik IVCS Ltd",
   "Selsella IVCS Ltd",
   "Shidakandi Bowabari IVCS Ltd",
   "Chibasal IVCS Ltd (Selsella)",
   "Homeland IVCS Ltd"
  ],
  "Tikrikilla": [
   "Chichang IVCS Ltd",
   "Dabanggre IVCS Ltd",
   "DKJB Union IVCS Ltd",
   "Fivestar IVCS Ltd",
   "Jakusan IVCS Ltd (Tikrikilla)",
   "Jangrapara IVCS Ltd",
   "Migasal IVCS Ltd",
   "Naguapara IVCS Ltd",
   "Nangrime IVCS Ltd (Tikrikilla)",
   "Pedaldoba IVCS Ltd",
   "Renggigre IVCS Ltd",
   "Rengsinpara IVCS Ltd",
   "Rongmali IVCS Ltd",
   "Saldoa IVCS Ltd",
   "Kissan IVCS Ltd",
   "Chibasal IVCS Ltd (Tikrikilla)",
   "Krimkro IVCS Ltd (Tikrikilla)",
   "Bakrime IVCS Ltd (Tikrikilla)"
  ]
 },
 "WJH": {
  "Amlarem": [
   "Darrang IVCS Ltd",
   "Jarain IVCS Ltd",
   "Khonglah IVCS Ltd",
   "Lakroh IVCS Ltd",
   "Lamin IVCS Ltd",
   "Moosakhia IVCS Ltd",
   "Muktapur IVCS Ltd",
   "Nongbarehrim IVCS Ltd",
   "Padu Bah IVCS Ltd",
   "Pamtbuh IVCS Ltd",
   "Shkenpyrsit IVCS Ltd",
   "Umladkhur IVCS Ltd",
   "Khihlang Boolang IVCS Ltd",
   "Syndai Kmai Shnong IVCS Ltd",
   "Umlangshor IVCS Ltd",
   "Nongtalang IVCS Ltd"
  ],
  "Laskein": [
   "Iakrehlang Saphai IVCS Ltd",
   "Thadsning IVCS Ltd",
   "Shiruplang Mynska IVCS Ltd",
   "Pynkulang IVCS Ltd",
   "Chiruplang Sahsniang IVCS Ltd",
   "Iakyntulang IVCS Ltd",
   "Iurim IVCS Ltd",
   "Kynronglang Umsalait IVCS Ltd",
   "Mukhap IVCS Ltd",
   "Khliehrangnah IVCS Ltd",
   "Khlookynrien IVCS Ltd",
   "Mowtyrshiah B IVCS Ltd"
  ],
  "Thadlaskein": [
   "Kremmyrsiang IVCS Ltd",
   "Ksehrynshang IVCS Ltd",
   "Madur IVCS Ltd",
   "Moodymmai IVCS Ltd",
   "Mookyndur IVCS Ltd",
   "Mookynniang IVCS Ltd",
   "Mukhla Nongrim IVCS Ltd",
   "Mupliang IVCS Ltd",
   "Mynsngat IVCS Ltd",
   "Namdong A IVCS Ltd",
   "Namdong B IVCS Ltd",
   "Nonglatem IVCS Ltd",
   "Niriang IVCS Ltd",
   "Nongrim Bambthong IVCS Ltd",
   "Phlongingkhaw IVCS Ltd",
   "Sohphoh IVCS Ltd",
   "Mukhnang IVCS Ltd",
   "Larnai IVCS Ltd",
   "Thadmusem IVCS Ltd",
   "Maskut IVCS Ltd",
   "Saitsama IVCS Ltd",
   "Moobakhon IVCS Ltd",
   "Wahiajer IVCS Ltd",
   "Khanduli IVCS Ltd",
   "Kdiap IVCS Ltd",
   "Nongkhroh IVCS Ltd",
   "Barato IVCS Ltd",
   "Madankynsaw IVCS Ltd"
  ],
  "Tikrikilla": [
   "Wegara IVCS Ltd"
  ]
 },
 "WKH": {
  "Laskein": [
   "Thadmuthlong IVCS Ltd"
  ],
  "Mawshynrut": [
   "Doranggre IVCS Ltd",
   "Ktieh Thawiar IVCS Ltd",
   "Langpih IVCS Ltd",
   "Langumshing A IVCS Ltd",
   "Nengchigre IVCS Ltd",
   "Nongdaju IVCS Ltd",
   "Nonglang IVCS Ltd",
   "Nongriangba IVCS Ltd",
   "Nongriangka Weilong IVCS Ltd",
   "Nongshram Adeng IVCS Ltd",
   "Nongshram Area IVCS Ltd",
   "Rongkhugre IVCS Ltd",
   "Seinduli IVCS Ltd",
   "Songsak IVCS Ltd",
   "Tynghor IVCS Ltd",
   "Umdang Area IVCS Ltd",
   "Umtap Area IVCS Ltd",
   "Umthlu IVCS Ltd",
   "Nongsleh Mawsaw IVCS LTD",
   "Kyrdum IVCS Ltd",
   "Hynriew Shnong Nongmisei IVCS Ltd",
   "Umsohpieng Myndo IVCS Ltd",
   "Mawdonglang IVCS LTD",
   "Hope IVCS Ltd",
   "Mawtynrong IVCS Ltd"
  ],
  "Nongstoin": [
   "Nonglwai IVCS Ltd",
   "Pyndeng Lawar IVCS Ltd",
   "Sangriang IVCS Ltd",
   "Mawkynrum IVCS Ltd"
  ]
 }
};
